### PR TITLE
main.text: fix typo

### PR DESCRIPTION
**Pull request by eliasnaur**

### CODE REVIEW

**Comment by eliasnaur** [comment]
Related, can you please update the PDF copy at https://secretcodex32.com/docs/2022-09-26--math.pdf? In particular, I'd like to see the updates from https://github.com/apoelstra/volvelle-math-companion/commit/3e00d989957beb0eadd10dbacca46a4a0f47311d.

**Comment by apoelstra** [comment]
Thank you!

And yep, I'll upload a new version to the site. I don't want to change the existing link because I prefer that the URLs with dates in them stay immutable.

**Comment by apoelstra** [comment]
Actually @eliasnaur I'm sorry, but could you re-open this PR to https://github.com/BlockstreamResearch/codex32/ ? The math companion now lives in the `mathematical-companion/` directory there.

I will update the README here.

**Comment by eliasnaur** [comment]
Done: https://github.com/BlockstreamResearch/codex32/pull/61

**Pull request closed without merging**
